### ISSUE TITLE
Mage registry key "_singleton/sheep_debug/observer" already exists

### ISSUE THREAD

**Issue by JoryHogeveen** [madalinoprea/magneto-debug#92]
Though I cleared all Magento cash (and even disabled it..) I still get the registry key error.

```
Trace:
#0 /app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /app/Mage.php(477): Mage::register('_singleton/shee...', false)
#2 /includes/src/__default.php(22158): Mage::getSingleton('sheep_debug/obs...')
#3 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('core_collection...', Array)
#4 /includes/src/__default.php(33182): Mage::dispatchEvent('core_collection...', Array)
#5 /includes/src/__default.php(32316): Mage_Core_Model_Resource_Db_Collection_Abstract->_beforeLoad()
#6 /includes/src/__default.php(34775): Varien_Data_Collection_Db->load(false, false)
#7 /includes/src/__default.php(31664): Mage_Core_Model_Resource_Website_Collection->load()
#8 /includes/src/__default.php(21467): Varien_Data_Collection->getItemById('0')
#9 /includes/src/__default.php(21299): Mage_Core_Model_App->_initStores()
#10 /includes/src/__default.php(21182): Mage_Core_Model_App->_initCurrentStore('', 'store')
#11 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /index.php(83): Mage::run('', 'store')
#13 {main}
```

**Comment by JoryHogeveen** [comment]
It was the Magento compiler.
Maybe add that in the Common Issues part?
